CREATE DATABASE BD_IBGE_LOCALIDADE2

GO

USE BD_IBGE_LOCALIDADE2

GO

CREATE TABLE REGIAO(
	ID INT NOT NULL,
	SIGLA VARCHAR(2),
	NOME VARCHAR(15),
	CONSTRAINT PK_REGIAO PRIMARY KEY (ID)
);

CREATE TABLE UF(
	ID INT NOT NULL,
	SIGLA VARCHAR(2),
	NOME VARCHAR(30),
	ID_REGIAO INT NOT NULL,
	CONSTRAINT PK_UF PRIMARY KEY(ID),
	CONSTRAINT FK_UF_REGIAO FOREIGN KEY (ID_REGIAO) REFERENCES REGIAO(ID)
);

CREATE TABLE MESORREGIAO(
	ID INT NOT NULL,
	NOME VARCHAR(100),
	ID_UF INT NOT NULL,
	CONSTRAINT PK_MESORREGIAO PRIMARY KEY(ID),
	CONSTRAINT FK_MESOR_UF FOREIGN KEY (ID_UF) REFERENCES UF(ID)
);

CREATE TABLE MICRORREGIAO(
	ID INT NOT NULL,
	NOME VARCHAR(100),
	ID_MESORREGIAO INT NOT NULL,
	CONSTRAINT PK_MICRORREGIAO PRIMARY KEY(ID),
	CONSTRAINT FK_MICROR_MESOR FOREIGN KEY (ID_MESORREGIAO) REFERENCES MESORREGIAO(ID)
);

CREATE TABLE MUNICIPIO(
	ID INT NOT NULL,
	NOME VARCHAR(100),
	ID_MICRORREGIAO INT NOT NULL,
	CONSTRAINT PK_MUNICIPIO PRIMARY KEY (ID),
	CONSTRAINT FK_PK_MUNICIPIO_MICROR FOREIGN KEY (ID_MICRORREGIAO) REFERENCES MICRORREGIAO(ID)
);

CREATE TABLE DISTRITO(
	ID INT NOT NULL,
	NOME VARCHAR(100),
	ID_MUNICIPIO INT NOT NULL,
	CONSTRAINT PK_DISTRITO PRIMARY KEY (ID),
	CONSTRAINT FK_DISTRITO_CIDADE FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO(ID)
);

CREATE TABLE REGIAO_INTERMEDIARIA(
	ID INT NOT NULL,
	NOME VARCHAR(100),
	ID_UF INT NOT NULL,
	CONSTRAINT PK_REGIAO_INTERMEDIARIA PRIMARY KEY (ID),
	CONSTRAINT FK_REGIAO_INTERMED_UF FOREIGN KEY (ID_UF) REFERENCES UF(ID)
);

CREATE TABLE REGIAO_IMEDIATA(
	ID INT NOT NULL,
	NOME VARCHAR(100),
	ID_REGIAO_INTERMEDIARIA INT NOT NULL,
	CONSTRAINT PK_REGIAO_IMEDIATA PRIMARY KEY (ID),
	CONSTRAINT FK_REGIAO_IMEDIATA_UF FOREIGN KEY (ID_REGIAO_INTERMEDIARIA) REFERENCES REGIAO_INTERMEDIARIA(ID)
);

ALTER TABLE MUNICIPIO ADD ID_REGIAO_IMEDIATA INT NOT NULL;

ALTER TABLE MUNICIPIO ADD CONSTRAINT FK_MUNICIPO_REG_IMED FOREIGN KEY (ID_REGIAO_IMEDIATA) REFERENCES REGIAO_IMEDIATA(ID);